version: "3.8"

services:
  app:
    image: golang:1.24.1-alpine
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app

    command: sh -c "go run ."

    ports:
      - "8080:8080"

    # environment:
    #   - PORT=8080
    # restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
